
on:
  push:
    branches: [main]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest  # Use a suitable runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to Dockerfile
          file: ./Dockerfile  # Specify Dockerfile name if not in root
          push: true
          tags: pseudonam/dummy:latest  # Replace with your image name and tag

